### ISSUE TITLE
Open Build  Folder - Location is not available

### ISSUE THREAD

**Issue by LechPa** [roslynpad/roslynpad#261]
I'm logged in as UserA. I would like to run RoslynPad as Administrator - so when I'm getting a login prompt I'm logging as UserB which has Admin rights.

When I click "Open Build  Folder", RoslynPad is trying to open directory:
C:\Users\UserA\AppData\Local\Temp\RoslynPad\Build\{some_guid}

It should open:
C:\Users\UserB\AppData\Local\Temp\RoslynPad\Build\{some_guid}
where the files are stored because  RoslynPad is run by UserB.

**Comment by aelij** [comment]
I used `runas` and RP tried to open the right folder (but failed because it didn't have permissions, which is expected). How do you know which folder it's trying to open? Using a debugger?

**Comment by LechPa** [comment]
I edited properties of the RP exe file - I checked option Run as Administrator. When I tried to run RP, login prompt appeared. I typed crededentials of UserB which has admin rights. When I clicked Open Build Folder I got a message that C:\Users\UserA\AppData\Local\Temp\RoslynPad\Build{some_guid} does not exist (or sth similar). I decided to switch the folder path in windows explored from:
C:\Users\**UserA**\AppData\Local\Temp\RoslynPad\Build{some_guid}
to:
C:\Users\**UserB**\AppData\Local\Temp\RoslynPad\Build{some_guid}
and I was able to browse RP files.

I'm not using runas, I'm running RP as a different user because of Run as Administrator setting.

**Comment by aelij** [comment]
Hmm. I'll have to check how "Run as Administrator" differs from "runas".
