### ISSUE TITLE
RoslynPAd in Window Workflow Foundation

### ISSUE THREAD

**Issue by shankey4u** [roslynpad/roslynpad#355]
Hello, how can I use RoslynPad in windows WF4.5

I have tried referring to the sample that you have provided. But somehow not able to figure out how to implement in Rehosted WF in WPF.

If possible, kindly provide a code snippet or some brief idea.
Thanks in Advance.

**Comment by aelij** [comment]
Please provide a code sample

**Comment by shankey4u** [comment]
Here is the link for the sample project
https://gitlab.com/pushpendra1/sampleworkflorehost.git

**Comment by shankey4u** [comment]
Hello, 
Any update on this.
Is it Possible??

**Comment by aelij** [comment]
While this should be possible unfortunately I don't have the resources to investigate. Sorry for the late response.
