### ISSUE TITLE
Does RoslynPad support running System.Diagnostics.Process ?

### ISSUE THREAD

**Issue by tuyen-at-work** [roslynpad/roslynpad#370]
Let say I want to run `git init` from RoslynPad:

```csharp
using System.Diagnostics;

await RunAsync("git", "init", @"E:\temp\test");
Console.WriteLine("DONE!");

public static Task<int> RunAsync(
    string fileName,
    string command,
    string workingFolder)
{
    var tcs = new TaskCompletionSource<int>();

    var currentDirectory = Directory.GetCurrentDirectory();

    Directory.CreateDirectory(workingFolder);
    Directory.SetCurrentDirectory(workingFolder);

    try
    {
        using var process = new Process
        {
            StartInfo =
                    {
                        FileName = fileName,
                        Arguments = command,
                        WorkingDirectory = workingFolder
                    }
        };

        process.Exited += (sender, args) =>
        {
            tcs.SetResult(process.ExitCode);
            process.Dispose();
        };

        process.Start();
        return tcs.Task;
    }
    finally
    {
        Directory.SetCurrentDirectory(currentDirectory);
    }
}
```

When execute above script using RoslynPad, I get following error:

```text
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\***\AppData\Local\Temp\roslynpad\build\613dd0a0687c45fea52cff91fcb900f7\bin\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\Users\***\AppData\Local\Temp\roslynpad\build\613dd0a0687c45fea52cff91fcb900f7\bin\rp-Program3.runtimeconfig.json file specifying the appropriate framework.
```

Does RoslynPad support above action? If it is, what I need to do to make above script work? Thanks!

**Comment by mitchcapper** [comment]
It would seem like you are on windows.  This does run without error for me but never returns (but newer version newer .net now so may be the difference for no error).  This is the same in roslynpad and in an actual console app (granted I am not using the init command but still).   A few items:

- You need [EnableRaisingEvents](http://msdn.microsoft.com/en-us/library/system.diagnostics.process.enableraisingevents.aspx) at a minimum if you want events.
- You do "using process" but then A) Call dispose in the event that doesn't fire, and B) have process go out of scope at the end of the try/catch block which will cause disposal while not done
- Your try/catch may not be doing what you want, as it finishes right after process.Start is called and not when the process ends.
- You don't need the directory changing as you are setting WorkingDirectory
- If you don't want to use events or your try catch block to wrap the entire lifetime  .NET 5 has WaitForExitAsync but if you are using another lower version Task.Run( () => process.WaitForExit() ); would work

Simplified and correctly working:
```csharp
Console.WriteLine("Hello, World!");
var code = await RunAsync("git", "init", @"E:\temp\test");
Console.WriteLine($"DONE: {code}!");
async Task<int> RunAsync(
	string fileName,
	string command,
	string workingFolder) {

	Directory.CreateDirectory(workingFolder);
	using var process = new Process {
		StartInfo = {
			FileName = fileName,
			Arguments = command,
			WorkingDirectory = workingFolder,
		}
	};
	process.Start();
	await process.WaitForExitAsync();
	return process.ExitCode;
}
```
