### ISSUE TITLE
.NET Framework x86/x64  - Error at run "ModuleInitializerAttribute" doesn't exist in the name space....

### ISSUE THREAD

**Issue by labichea** [roslynpad/roslynpad#408]
When running a small code and choosing .Net Framework x86 or x64. An immediate error 

OS: WINDOWS 10 21H1 - Visual Studio 2019

CS0234: The type or namespace name 'ModuleInitializerAttribute' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)

When choosing .Net 5 - Run works.

**Comment by aelij** [comment]
Please do not ignore the issue template.

**Comment by qinqoushui** [comment]
在private Compiler CreateCompiler(string code, OptimizationLevel? optimizationLevel) 函数 中
将
```
 if ( Platform.FrameworkVersion?.Major < 5)
```
修改为：
```
 if ( !Platform.IsCore ||  Platform.FrameworkVersion?.Major < 5)
                {
                  ...
                }
```
