### ISSUE TITLE
Error building with VS2022 or dotnet

### ISSUE THREAD

**Issue by jogibear9988** [roslynpad/roslynpad#413]
I try to build "main" Branch with .NET 6 or VS2022 and get following output (only a small part of it

	D:\csharp\git\github\common\RoslynPad>dotnet build -bl -c Release -m:1 src/RoslynPad.sln
	Microsoft (R)-Build-Engine, Version 17.0.0+c9eb9dd64 für .NET
	Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

	C:\Program Files\dotnet\sdk\6.0.100\MSBuild.dll -bl -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.100\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.100\dotnet.dll -maxcpucount -m:1 -property:Configuration=Release -restore -verbosity:m src/RoslynPad.sln
	  Wiederherzustellende Projekte werden ermittelt...
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Runtime\RoslynPad.Runtime.csproj" wiederhergestellt (in "1,21 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn.Avalonia\RoslynPad.Roslyn.Avalonia.csproj" wiederhergestellt (in "38,84 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Common.UI\RoslynPad.Common.UI.csproj" wiederhergestellt (in "38,86 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Build\RoslynPad.Build.csproj" wiederhergestellt (in "38,84 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad\RoslynPad.csproj" wiederhergestellt (in "38,88 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Editor.Windows.Test\RoslynPad.Editor.Windows.Test.csproj" wiederhergestellt (in "38,89 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Editor.Avalonia\RoslynPad.Editor.Avalonia.csproj" wiederhergestellt (in "34 ms").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj" wiederhergestellt (in "1,42 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Avalonia\RoslynPad.Avalonia.csproj" wiederhergestellt (in "44,06 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn.Windows\RoslynPad.Roslyn.Windows.csproj" wiederhergestellt (in "47,24 sec").
	  "D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Editor.Windows\RoslynPad.Editor.Windows.csproj" wiederhergestellt (in "48,5 sec").
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\CodeRefactorings\PasteTrackingService.cs(1,30): error CS0234: Der Typ- oder Namespacename "PasteTracking" ist im Namespace "Microsoft.CodeAnalysis" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.) [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\QuickInfo\QuickInfoProvider.cs(11,30): error CS0234: Der Typ- oder Namespacename "ExternalAccess" ist im Namespace "Microsoft.CodeAnalysis" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.) [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\SignatureHelp\PythiaSignatureHelpProviderImplementation.cs(7,30): error CS0234: Der Typ- oder Namespacename "ExternalAccess" ist im Namespace "Microsoft.CodeAnalysis" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.) [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\CodeRefactorings\PasteTrackingService.cs(8,43): error CS0246: Der Typ- oder Namespacename "IPasteTrackingService" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\CodeRefactorings\PasteTrackingService.cs(7,20): error CS0246: Der Typ- oder Namespacename "IPasteTrackingService" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\Diagnostics\AnalyzerAssemblyLoaderWrapper.cs(10,26): error CS0122: 'Der Zugriff auf "DefaultAnalyzerAssemblyLoader" ist aufgrund des Schutzgrads nicht möglich. [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\LanguageServices\ChangeSignature\ChangeSignatureDialogViewModel.cs(340,20): error CS0246: Der Typ- oder Namespacename "ExistingParameter" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\LanguageServices\ChangeSignature\ChangeSignatureDialogViewModel.cs(343,102): error CS0246: Der Typ- oder Namespacename "ExistingParameter" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]
	D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\LanguageServices\ExtractInterface\ExtractInterfaceOptionsService.cs(58,54): error CS0426: Der Typname "ExtractLocation" ist im Typ "ExtractInterfaceOptionsResult" nicht vorhanden. [D:\csharp\git\github\common\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]

**Comment by aelij** [comment]
The CI build is working. Clean your directories and try again.
Also please do not ignore the issue templates.

**Comment by jogibear9988** [comment]
I saw that it is workin and only using net6.
But I did a clean, and the error is still there.
Maybe multiple .Net Versions on a Computer produce an error...

wich Version of Microsoft.CodeAnalysis is used on your side?

**Comment by jogibear9988** [comment]
@aelij maybe you could help:

I still can not build, and see that the GitHub Action is building yours.

But when I analyze my errors, I see this is the first error:

D:\RoslynPad\src\RoslynPad.Roslyn\CodeRefactorings\PasteTrackingService.cs(1,30): error CS0234: Der Typ- oder Namespacename "PasteTracking" ist im Namespace "Microsoft.CodeAnalysis" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.) [D:\RoslynPad\src\RoslynPad.Roslyn\RoslynPad.Roslyn.csproj]

so I looked, and I find this:
https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/PasteTracking/IPasteTrackingService.cs

how could you implement this interface when it is internal?
