### ISSUE TITLE
Not able to compile in Net6 Environment

### ISSUE THREAD

**Issue by jogibear9988** [roslynpad/roslynpad#414]
**Describe the bug**

I'm not able to compile "main" branch under net6 environment.
I see that your Github Action works, but I don't see why mine build does not.
And I also don't understand how could yours work in the first place?
You use an internal interface from roslyn: "IPasteTrackingService"
https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/PasteTracking/IPasteTrackingService.cs
in this file: https://github.com/roslynpad/roslynpad/blob/main/src/RoslynPad.Roslyn/CodeRefactorings/PasteTrackingService.cs

I see that your build works, but why?

**To Reproduce**

don't know, it does not work on my machine

**Expected behavior**

does work, but don't know why

**Version**
- OS: Windows 10
- Build (or commit ID if built from source): 6931ebb

**Comment by jogibear9988** [comment]
I don't get it... I look at your source, your csproj files...
I only see this:

       https://github.com/roslynpad/roslynpad/blob/main/Directory.Build.props#L15

And if I look in the Codeanalysis Dll s in this Version, I only see the interface is internal

**Comment by aelij** [comment]
I'm using https://github.com/aelij/IgnoresAccessChecksToGenerator to access internals.

Sorry but I don't have bandwidth to help you debug this right now. It must be some configuration on your machine.

**Comment by jogibear9988** [comment]
@aelij maybe that helps... I need to look.
So I think that is not called.
Do you use VS2022? Okay I could also not build using "dotnet" commandline tool...
I'll invenstigate more...

**Comment by jogibear9988** [comment]
I'll got it to work...

Problem is, clean build of solution does not remove this folder:

src\RoslynPad.Roslyn\obj\GeneratedPublicizedAssemblies
so in this were still some old dll's

![image](https://user-images.githubusercontent.com/364896/142027603-7276094f-86d9-42d5-bf4f-e7f513bfb5d8.png)

after deleting it manually it worked

**Comment by jogibear9988** [comment]
I've created an issue about maybe cleaning the old dll's (if possible)

**Comment by jogibear9988** [comment]
Thanks for your help!

**Comment by blakepell** [comment]
@jogibear9988 - Thank you for sharing the fix, I was just having the same issue was scratching my head as to what caused it.
