### ISSUE TITLE
Request for a Stop button

### ISSUE THREAD

**Issue by DamianSuess** [roslynpad/roslynpad#415]
**Describe the solution you'd like**
As a user, I'd like to have the ability to stop the running process via a Stop button. This would allow the user to kill the operation of dotnet app in progress.

**Describe alternatives you've considered**
The current alternative is to find the `dotnet` process and kill it via Task Manager.

**Additional context**
Sample mini-app:

```cs
bool tryAgain = true;
do
{
  if (1 == 0)
    tryAgain = false;
} while (tryAgain);
```

**Comment by aelij** [comment]
This already exists, it's just called "restart process". I've already renamed it to Stop and changed the icon in the main branch.

**Comment by DamianSuess** [comment]
Thank you, @aelij, I apologize for wasting your time.

The name "restart" mislead me that it started again versus stopping. Also, in the example case, it ran so quickly that the output was still waiting to catch-up. 

Thank you again for updating the main branch, looking forward to it. Keep up the great work!! I love this as a scratch pad.
