### ISSUE TITLE
Unexpected character encountered when using Selenium

### ISSUE THREAD

**Issue by Roemer** [roslynpad/roslynpad#418]
**Describe the bug**
When Selenium is used, the script seems to apruptly abort immediately as soon as `driver.Quit()` is called. Even any console output after the initialization of the `IWebDriver` is not shown at all.

**To Reproduce**
Use the following script:
```cs
#r "nuget:Selenium.WebDriver.ChromeDriver/97.0.4692.7100"
#r "nuget:Selenium.WebDriver/4.1.0"

using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

Console.WriteLine("Test1");
IWebDriver driver = new ChromeDriver();
Console.WriteLine("Test2");
driver.Quit();
Console.WriteLine("Test3");
```
**Expected behavior**
The three messages are written to the console and the script is finishing.

**Observed behavior**
Only the first message is printed and then the exception `Unexpected character encountered while parsing value: S. Path '', line 0, position 0.` occurs and the script is stopped.

**Version**
- OS: Windows 10, Windows 11
- Build (or commit ID if built from source): Release 15.1
- Framework: .NET Core 6.0.100, same with .NET Framework x64 or .NET Core 3

**Comment by jboinembalome** [comment]
I tested the script with the release 15.1 and I also have the error with the following version of ChromeDriver:
`#r "nuget:Selenium.WebDriver.ChromeDriver/100.0.4896.6000"`

However, the three messages are written to the console and the script is finishing on the last commit f1fffd3 :
![Test Selenium](https://user-images.githubusercontent.com/70820612/162253387-e7e25119-57b9-492a-bed9-f36a270922fd.PNG)


Therefore, the problem should be solved on the next release.

**Comment by aelij** [comment]
Closing as it is indeed working now
