### ISSUE TITLE
not working on MacOS ARM

### ISSUE THREAD

**Issue by LeviLv** [roslynpad/roslynpad#421]
**Describe the bug**

> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libAvaloniaNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibAvaloniaNative, 1): image not found
   at Avalonia.Native.AvaloniaNativePlatform.CreateAvaloniaNative()
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(AvaloniaNativePlatformOptions options)
   at Avalonia.AvaloniaNativePlatformExtensions.<>c__DisplayClass0_0`1.<UseAvaloniaNative>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at RoslynPad.Program.Main(String[] args) in C:\Source\github\aelij\RoslynPad\src\RoslynPad.Avalonia\Program.cs:line 13

**To Reproduce**
dotnet RoslynPadAvalonia/RoslynPad.dll

**Expected behavior**

**Version**
- OS:  MacOS BigSur 11.6 （Apple Silicon）
- Build (or commit ID if built from source):

**Comment by LeviLv** [comment]
SDK Version : 6.0.101

**Comment by aelij** [comment]
As I don't have an M1, could you please clone the repo, change `AvaloniaVersion` to 0.10.12 in [this file](https://github.com/roslynpad/roslynpad/blob/main/Directory.Build.props) and try to run the RoslynPad.Avalonia project?

**Comment by dahlia** [comment]
I'm using MacBook Pro with M1 Pro and it apparently works well.

<img width="1104" alt="RoslynPad 17 on Apple silicon Mac" src="https://user-images.githubusercontent.com/12431/203493464-043cb97b-746f-4c85-978d-64d7ea87b0ca.png">

The source tree I built is at 86d296ea8045806e364faef615e444a44970beca.  My .NET SDK is 7.0.100.  The below is how I built it:

```console
git clone https://github.com/roslynpad/roslynpad.git
git reset --hard 86d296ea8045806e364faef615e444a44970beca
cd roslynpad/src/RoslynPad.Avalonia/
dotnet build
dotnet run
```

However, the official build (either _RoslynPad.dll_ and _RoslynPad.exe_) inside the zip file does not work:

```console
$ cd RoslynPad/
$ dotnet RoslynPad.exe
You must install or update .NET to run this application.

App: /Users/dahlia/Downloads/RoslynPad/RoslynPad.exe
Architecture: arm64
Framework: 'Microsoft.WindowsDesktop.App', version '3.1.0' (arm64)
.NET location: /usr/local/share/dotnet/

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=3.1.0&arch=arm64&rid=osx.13-arm64
$ dotnet RoslynPad.dll 
You must install or update .NET to run this application.

App: /Users/dahlia/Downloads/RoslynPad/RoslynPad.dll
Architecture: arm64
Framework: 'Microsoft.WindowsDesktop.App', version '3.1.0' (arm64)
.NET location: /usr/local/share/dotnet/

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=3.1.0&arch=arm64&rid=osx.13-arm64
```

IMHO it should be distributed in a separated file.

**Comment by aelij** [comment]
Thanks @dahlia. I will include a binary in the upcoming release
