### ISSUE TITLE
Null reference from code assistance?

### ISSUE THREAD

**Issue by sunny-lan** [roslynpad/roslynpad#423]
**Describe the bug**
I get a null reference if I enter this code in the edtior after a few seconds:
```csharp
void func(){
}
Console.CancelKeyPress+=func;
```

Call stack
![image](https://user-images.githubusercontent.com/14915260/156905628-bb8e70a2-cd13-460a-a551-b78e6264b7ec.png)

**To Reproduce**
This is the code to setup the host:
```csharp
rosylnHost = new RoslynHost(
                    references: RoslynHostReferences.NamespaceDefault.With(
                        typeNamespaceImports: new[] {
                            typeof(ScriptContext),
                        },
                        assemblyReferences: new[]
                        {
                            typeof(object).Assembly,
                            typeof(System.Console).Assembly,
                            typeof(System.Linq.Enumerable).Assembly,
                            typeof(BotCtx).Assembly,
                            typeof(app.core.logs).Assembly,
                            typeof(System.Text.RegularExpressions.Regex).Assembly,
                        }
                    ),
                    additionalAssemblies: new[]
                    {
                        Assembly.Load("RoslynPad.Roslyn.Windows"),
                        Assembly.Load("RoslynPad.Editor.Windows")
                    }
                );
//...
            editor.Initialize(app.rosylnHost, new ClassificationHighlightColors(), Directory.GetCurrentDirectory(), "");
```

**Expected behavior**
It doesn't crash

**Version**
- OS: Windows 10
- Build (or commit ID if built from source): 1.2.0

**Comment by jboinembalome** [comment]
After some testing, it seems that it does not work on the version 1.2.0 as you say but there is no problem on the last commit f1fffd3:

![Test on current build](https://user-images.githubusercontent.com/70820612/162072622-237024bb-8ac8-41f7-a946-1297c9bc5906.png)

Therefore, the next update of the RoslynPad.Editor.Windows package should solve the null reference.

Hope this answer helps!

**Comment by aelij** [comment]
Closing as this seems to be fixed in `main`
