### ISSUE TITLE
How can i fix it?

### ISSUE THREAD

**Issue by Zina03** [roslynpad/roslynpad#425]
![image](https://user-images.githubusercontent.com/90962366/160290848-b1dcba0c-7247-488a-8877-8a9d0fb4173a.png)

**Comment by DamianSuess** [comment]
@Zina03, could you provide a more detailed description of your issue?
* What is your development environment (VS version, etc.)
* Is this from a clean repo pull and build?
* Which .NET version do you have installed on your machine?  `dotnet --list-sdks`

**Comment by aelij** [comment]
Closing as we got no response to Damian's good questions.
Also, please avoid screenshots, we should not have to type letters from pictures to help.
