### ISSUE TITLE
Update Nuget package

### ISSUE THREAD

**Issue by FrisbeeBigger** [roslynpad/roslynpad#426]
Hello. I noticed that updating the repository
happens regularly, but
Nuget package has not been updated for a long time. Could you update the Nuget package?

**Comment by jogibear9988** [comment]
@aelij any news about new nugets?

**Comment by JanTamis** [comment]
see #403 im afraid this will not happen in the near future

**Comment by jogibear9988** [comment]
okay, I'll look to release some of the main branch

**Comment by aelij** [comment]
Will be updated with upcoming release. Note that the new packages will only support .NET 6 and above (in accordance with the [.NET support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)).
