### ISSUE TITLE
Add support for CLI usage

### ISSUE THREAD

**Issue by stebaker92** [roslynpad/roslynpad#437]
**Describe the solution you'd like**
It would be great to run files in a non-interactive way. For example, something like this from the command line:

`roslynpad.exe -f my-script.csx`

I've looked into using commandline based tools that support `csx` files but the files that RoslynPad generates doesn't seem to be compatible with tools like `ScriptCS ` or `dotnet-script` as the NuGet include syntax is slightly different (RoslynPad uses `#r "nuget: Newtonsoft.Json/13.0.1"` whereas dotnet-script uses a comma - `#r "nuget: Newtonsoft.Json, 13.0.1"`) 

**Describe alternatives you've considered**
Linqpad has a similar feature, `lprun`. See 
https://www.linqpad.net/lprun.aspx

**Additional context**
I write a lot of small dev scripts, would be great to use the RoslynPad GUIto write and test scripts then consume them via my terminal

**Comment by fakhrulhilal** [comment]
I agree. RoslynPad is great editor, small and lightweight. It would be nice if we can use that to code C# script (rather than relying on VScode) and execute the script using another script runner (like `dotnet-script` above). I use powershell for my daily scripting, but still, C# is better than PSscript.

**Comment by aelij** [comment]
I actually aligned RP with the dotnet-script NuGet reference format a while ago (it's also what appears in the "Script & Interactive" on nuget.org), so it should be compatible. Given that, I don't see a point in creating another CLI.

**Comment by stebaker92** [comment]
Thank you for the response:

> I actually aligned RP with the dotnet-script NuGet reference format a while ago (it's also what appears in the "Script & Interactive" on nuget.org), so it should be compatible

I'm not sure if something has changed but it is no longer compatible. The format on [dotnet-script](https://github.com/dotnet-script/dotnet-script#nuget-packages-1) is:
 `#r "nuget: AutoMapper, 6.1.0"`
and the format on [NuGet.org](https://www.nuget.org/packages/AutoMapper) is 
`#r "nuget: AutoMapper, 12.0.0"` 

The format in Roslynpad contains a slash, making it incompatible with dotnet-script:
`"nuget: Newtonsoft.Json/13.0.1"`  


> Given that, I don't see a point in creating another CLI
I would argue that because the format is incompatible, RoslynPad scripts using NuGet packages are difficult to run from the command line without doing workarounds and `dotnet-script` (or similar tools) can't be used for scripts that reference nuget packages. I'd be happy to have a go implementing CLI support when I get some time spare

**Comment by fakhrulhilal** [comment]
> I'm not sure if something has changed but it is no longer compatible. The format on [dotnet-script](https://github.com/dotnet-script/dotnet-script#nuget-packages-1) is: `#r "nuget: AutoMapper, 6.1.0"` and the format on [NuGet.org](https://www.nuget.org/packages/AutoMapper) is `#r "nuget: AutoMapper, 12.0.0"`
> 
> The format in Roslynpad contains a slash, making it incompatible with dotnet-script: `"nuget: Newtonsoft.Json/13.0.1"`
the command line without doing workarounds and `dotnet-script` (or similar tools) can't be used for scripts that reference nuget packages. I'd be happy to have a go implementing CLI support when I get some time spare

I guess it's in progress now. I see the main branch use comma separated for nuget package. It's just not released yet. It's still has another bug I guess.
