### ISSUE TITLE
#load don't work

### ISSUE THREAD

**Issue by qinqoushui** [roslynpad/roslynpad#440]
**Describe the bug**
 it work in 15.1,but in 16,The code says normal, but there is an error at runtime

**To Reproduce**
- test.cs
```
public class Test
{
	public static string Hello="aa";
}
```
- test.csx
```
#load   "d:\temp\test.cs" 
Console.WriteLine(Test.Hello);
```
![image](https://user-images.githubusercontent.com/5665679/183241240-0c6f8e2f-4e65-4415-b0f7-eb446263c327.png)

**Expected behavior**

**Version**
- OS:
- Build (or commit ID if built from source):

**Comment by aelij** [comment]
Seems to be working in the latest version (18). Please reopen if it doesn't.
