### ISSUE TITLE
Import LINQPad's .Linq files

### ISSUE THREAD

**Issue by Arithmomaniac** [roslynpad/roslynpad#441]
Instead of starting with #r for imports, a LinqPad file starts with an XML metadata block like the following:

```xml
<Query Kind="Statements">
  <NuGetReference>CsvHelper</NuGetReference>
  <Namespace>CsvHelper</Namespace>
  <Namespace>CsvHelper.Configuration</Namespace>
</Query>
```

It would be nice to be able to "import" these .linq files, converting them into .csx files and opening them in RoslynPad.

**Comment by aelij** [comment]
Thanks for the suggestion but LINPad is a commercial product, and I don't know the implications of such a thing, so rather avoid it :)
