### ISSUE TITLE
Version 4.4.0 NuGet Problem

### ISSUE THREAD

**Issue by AlexeiScherbakov** [roslynpad/roslynpad#450]
**Describe the bug**

Visual Studio see 4.4.0 package but NuGet can't download it. Project has framework net7.0-windows

Even when I downloaded package and place it in local feed VS see 4.4.0 package but NuGet don't see

**To Reproduce**

**Expected behavior**

**Version**
- OS: Windows 11
- Build (or commit ID if built from source): 4.4.0

![изображение](https://user-images.githubusercontent.com/8665915/206372876-2618e555-9ce9-480b-b170-acedff066667.png)

I look inside NuGet package and see:
![изображение](https://user-images.githubusercontent.com/8665915/206374119-df7818e7-317f-4b8c-8c1b-3467e5e63c35.png)

Target framework moniker is incorrect. It should be net6.0-windows

**Comment by aelij** [comment]
The problem was not `windows7.0` - that was automatically added by `dotnet pack`. It's that I neglected to publish `RoslynPad.Roslyn.Windows` :) Fixed now, thanks.

I also update the REPL sample to use the latest packages (and .NET 7.0).
