### ISSUE TITLE
XAML design data is pointing to a missing file

### ISSUE THREAD

**Issue by kwcoffee1** [roslynpad/roslynpad#452]
**Describe the bug**
When viewing a XAML files that contains the follow designtime data tag is displaying "Invalid Markup" message.
             d:DataContext="{d:DesignInstance ui:MainViewModel}"

**To Reproduce**
Look at XAML File RoslynPad.DocumentTreeView and others with VS 2022 ver. 17

**Expected behavior**
A xaml view with default data.

**Version**
Roslyn 17

- OS: Windows 11
- Build (or commit ID if built from source):

**Comment by aelij** [comment]
@kwcoffee1 Thanks for the report but I don't use the designer so it's not a priority for me :) It's possible this is because of dependency injection in the view model.
