### ISSUE TITLE
#load path/Script.csx is not working in RoslynPad 17.

### ISSUE THREAD

**Issue by kwcoffee1** [roslynpad/roslynpad#453]
**Describe the bug**
Script Editor directive: #load path/Script.csx is not working in RoslynPad 17.

**To Reproduce**
Create a C# script file and linking to it in another file as shown above.

**Expected behavior**
The linked file should have access to the methods and properties in file Script.csx.
**Version**
- OS: Window 11
- RoslynPad: 17

- Build (or commit ID if built from source):
Command #r works but not #load.

**Comment by aelij** [comment]
Duplicate of #440
