### ISSUE TITLE
Release Mode

### ISSUE THREAD

**Issue by robdplatt** [roslynpad/roslynpad#454]
**Describe the solution you'd like**
Please add toggle for debug/release mode. It would be nice to be able to run quick benchmarks on snippits of code. BenchmarkDotNet requires release mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by aelij** [comment]
RoslynPad has a toggle for turning on compiler optimizations. There's no concept of "release" as it doesn't use MSBuild for building. See this comment https://github.com/roslynpad/roslynpad/issues/285#issuecomment-1380025385 for a working example.
