### ISSUE TITLE
Repl sample build error

### ISSUE THREAD

**Issue by ondutya** [roslynpad/roslynpad#461]
**Describe the bug**
build repl sample use VS2022 
Error	NU1604	Warning As Error: Project dependency Microsoft.SourceLink.GitHub does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.	RoslynPadReplSample	D:\Code\Github_Roslyn\roslynpad\samples\RoslynPadReplSample\RoslynPadReplSample.csproj	1	
![image](https://user-images.githubusercontent.com/4124472/224232976-bceb8cbb-ae3d-43c1-aa9d-756751d3557c.png)

**Comment by aelij** [comment]
Fixed in 1958cfbc796a42e64013e86426e290adc4272bbb
