### ISSUE TITLE
Publish macOS version as an app bundle

### ISSUE THREAD

**Issue by kawazoe** [roslynpad/roslynpad#464]
**Describe the solution you'd like**
Typically, macOS applications are distributed in an app bundle: https://docs.avaloniaui.net/docs/distribution-publishing/macos

**Describe alternatives you've considered**
As someone new to avalonia, I have no clue on how to properly integrate the current package in my desktop environement. It won't show up in LaunchPad. I can't pin it to the dock, etc...

Having to run it from the terminal every time is cumbersome.

EDIT: Bypassing security warning is also not obvious as the usual tricks do not apply.

**Comment by aelij** [comment]
Fixed in v19
