### ISSUE TITLE
Invalid app configuration crashes the app on startup

### ISSUE THREAD

**Issue by clarktrip3** [roslynpad/roslynpad#468]
I installed the app from the Microsoft Store on a Windows 10 Pro 22H2 system today.  After installation, the app will not fully open.  It opens a white window that shows on the taskbar.  When I click in it, nothing happens.

To reproduce, install it on a Windows 10 Pro system and try to open it.  I've been doing this since summer 2022.

I expect the app to open.

I don't see the version, but I've been trying for 10 months.
- OS: 
Edition	Windows 10 Pro
Version	22H2
Installed on	‎2/‎17/‎21
OS build	19045.2913
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by KieranDevvs** [comment]
I've also experienced this twice now.
I don't remember the exact cause but from what I recall, the issue felt like it was that the window size is set to 0x0.

Check  `%userprofile%/Documents/RoslynPad/RoslynPad.json`
You should see some property configs for the UI e.g:
```json
{
  "sendErrors": true,
  "enableBraceCompletion": true,
  "latestVersion": "15.1",
  "windowBounds": "990,0,938,780",
  "dockLayout": "<LayoutRoot>\r\n  <RootPanel Orientation=\"Horizontal\">\r\n    <LayoutAnchorablePane Id=\"f084e152-0aec-4cce-b80e-5cb156c2e8c7\" Name=\"Documents\" DockWidth=\"200\" />\r\n    <LayoutDocumentPane Id=\"74ab9b80-1adc-4668-91af-4c52616cc448\">\r\n      <LayoutDocument Title=\"New.cs\" IsSelected=\"True\" IsLastFocusedDocument=\"True\" LastActivationTimeStamp=\"04/29/2023 18:26:03\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n      <LayoutDocument Title=\"New.cs\" />\r\n    </LayoutDocumentPane>\r\n  </RootPanel>\r\n  <TopSide />\r\n  <RightSide />\r\n  <LeftSide>\r\n    <LayoutAnchorGroup PreviousContainerId=\"f084e152-0aec-4cce-b80e-5cb156c2e8c7\">\r\n      <LayoutAnchorable CanHide=\"False\" AutoHideWidth=\"200\" AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Documents\" ContentId=\"DocumentTree\" CanFloat=\"False\" LastActivationTimeStamp=\"03/23/2023 23:15:06\" />\r\n    </LayoutAnchorGroup>\r\n  </LeftSide>\r\n  <BottomSide />\r\n  <Hidden />\r\n</LayoutRoot>",
  "windowState": "Maximized",
  "editorFontSize": 12,
  "liveModeDelayMs": 2000,
  "defaultPlatformName": "",
  "formatDocumentOnComment": true
}
```

I'm pretty sure deleting this config file and restarting the app forces it to be regenerated with default values and thus the UI appears. **Before you do this, can you please post your config in this issue thread so we can attempt to investigate the problem**

**Comment by clarktrip3** [comment]
Here is the contents of RoslynPad.json.
{
  "sendErrors": true,
  "enableBraceCompletion": true,
  "latestVersion": "15.1",
  "windowBounds": "408,1098,1487,987",
  "dockLayout": "<LayoutRoot>\r\n  <RootPanel Orientation=\"Horizontal\">\r\n    <LayoutAnchorablePane Id=\"436812f2-eab8-4313-8b53-656239a42197\" Name=\"Documents\" DockWidth=\"200\" />\r\n    <LayoutDocumentPane Id=\"c0d19623-d37e-415a-9ed2-8444c454dcd6\">\r\n      <LayoutDocument Title=\"New.cs\" IsSelected=\"True\" IsLastFocusedDocument=\"True\" LastActivationTimeStamp=\"04/28/2023 06:40:40\" />\r\n    </LayoutDocumentPane>\r\n  </RootPanel>\r\n  <TopSide />\r\n  <RightSide />\r\n  <LeftSide>\r\n    <LayoutAnchorGroup PreviousContainerId=\"436812f2-eab8-4313-8b53-656239a42197\">\r\n      <LayoutAnchorable CanHide=\"False\" AutoHideWidth=\"200\" AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Documents\" ContentId=\"DocumentTree\" CanFloat=\"False\" LastActivationTimeStamp=\"07/09/2021 15:16:12\" />\r\n    </LayoutAnchorGroup>\r\n  </LeftSide>\r\n  <BottomSide />\r\n  <Hidden />\r\n</LayoutRoot>",
  "windowState": "Normal",
  "editorFontSize": 12,
  "liveModeDelayMs": 2000,
  "defaultPlatformName": "",
  "formatDocumentOnComment": true
}

**Comment by aelij** [comment]
Thanks, will try to repro this

**Comment by aelij** [comment]
I can't repro this using the provided configuration in the latest version. If it's still applicable, please reopen and try to get a stack trace. Thanks
