### ISSUE TITLE
Csx files are compiled like cs files

### ISSUE THREAD

**Issue by xparadoxical** [roslynpad/roslynpad#471]
I noticed that one of my older scripts can't be run anymore.

**To Reproduce**
Create a new document (.cs) and a new script document (.csx). Paste the following code in both files:
```cs
static void M(int i) => M();
static void M() {}
```
In .cs there are wavy underlines visible. After trying to run it, there are 3 errors and 1 warning.
In .csx there are no warnings or errors visible right away. After trying to run it, you can see the same 3 errors and 1 warning that were produced by the .cs file.

**Expected behavior**
The .csx file should run, it's valid code for MS.CA.Scripting. The two methods are type members.
The .cs file should not compile. The two methods are local functions, which can't have overloads.

**Version**
- OS: win11
- Build (or commit ID if built from source): latest from ms store

**Comment by aelij** [comment]
Thanks for reporting it! Should be fixed in the next release.
