### ISSUE TITLE
Dll not loading into a 64-bit window project.

### ISSUE THREAD

**Issue by kwcoffee1** [roslynpad/roslynpad#475]
**Describe the bug**
IL format error, I need the code to compile to a 64-bit WPF library image.
The code compiles successfully, but will not load in my 64-bit WPF app.

The error message is:
System.BadImageFormatException: 'Bad IL format. The format of the file MyDLL is invalid.'

**To Reproduce**
N/A

**Expected behavior**
Load when executing:  var dll = Assembly.LoadFrom(DLLName);

**Version**
RoslynPad 18, 4.4.0

- OS:  Windows 11
- Build (or commit ID if built from source):

**Comment by aelij** [comment]
Hi, please see this comment: https://github.com/roslynpad/roslynpad/issues/469#issuecomment-1530139010
I will fix it when I upgrade Roslyn.

**Comment by aelij** [comment]
This works for me. It must be a problem with that specific DLL. Most probably its bitness (32 vs 64). Try this in VS as well.
