### ISSUE TITLE
Missed RoslynPad namespace errors

### ISSUE THREAD

**Issue by SergeyKotyushkin** [roslynpad/roslynpad#478]
**Describe the bug**
Cannot run any code after upgrading to 18 version.

Code:
```cs
1.Dump();
```

Output:
```
CS0246: The type or namespace name 'RoslynPad' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'RoslynPad' could not be found (are you missing a using directive or an assembly reference?)
CS1061: 'int' does not contain a definition for 'Dump' and no accessible extension method 'Dump' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)
CS0103: The name 'RoslynPad' does not exist in the current context
```

**To Reproduce**
Write any code. Use 18 version.

**Expected behavior**
Code works.

**Version**
- OS: Windows 10
- Build (or commit ID if built from source): 18 version

**Comment by dylbarne** [comment]
was able to temporarily fix by adding to script file:
`#r "C:\Users\...\AppData\Local\Temp\roslynpad\...\bin\RoslynPad.Runtime.dll"`
(filling in actual full path to wherever your **RoslynPad.Runtime.dll** is located)

**Comment by aelij** [comment]
Thanks for reporting this! Those files are missing in the Microsoft Store version. I've pushed an update, hopefully it would be available in a day or two.
