### ISSUE TITLE
'No export was found for the contract ...' in 3rd party app

### ISSUE THREAD

**Issue by Eideren** [roslynpad/roslynpad#501]
**Describe the bug**
Exception
```
System.Composition.Hosting.CompositionFailedException: 'No export was found for the contract 'IDiagnosticService'
 -> required by import 'inner' of part 'DiagnosticsService'
 -> required by initial request for contract 'IDiagnosticService''
```
When calling `GetService<IDiagnosticService>()` in `RoslynHost`.

**Additional Information**

Hey, I'm one of the maintainers for the [Stride game engine](https://github.com/stride3d/stride). We've been using your wonderful project for a while now. The repo owner, xen2, came in a couple years back to open a bunch of PRs. He's not really available right now so I'm investigating this issue on his behalf, but I'm a bit out of my debt here I must admit.

- We've recently moved things from net6 to net8 and that issue started popping up from then on.
- I can compile and run your editor flawlessly, so it seems likely that something on our end or some changes in net8 broke something that roslynpad requires when running through our editor.
- I've tried running with the net8 nuget packages and upgrading other packages appropriately, but that issue persist.

The first `GetService` call that errors out occurs right here https://github.com/stride3d/stride/blob/master/sources/editor/Stride.Assets.Presentation/AssetEditors/ScriptEditor/RoslynWorkspace.cs#L38 in our source.

The callstack looks like so:

- [AssetEditors.ScriptEditor.RoslynHost.GetService<RoslynPad.Roslyn.Diagnostics.IDiagnosticService>() Line 109](https://github.com/stride3d/stride/blob/master/sources/editor/Stride.Assets.Presentation/AssetEditors/ScriptEditor/RoslynHost.cs#L109)
- [AssetEditors.ScriptEditor.RoslynWorkspace.RoslynWorkspace(Stride.Assets.Presentation.AssetEditors.ScriptEditor.RoslynHost host) Line 38](https://github.com/stride3d/stride/blob/master/sources/editor/Stride.Assets.Presentation/AssetEditors/ScriptEditor/RoslynWorkspace.cs#L38)
- [AssetEditors.ScriptEditor.RoslynHost.RoslynHost() Line 50](https://github.com/stride3d/stride/blob/master/sources/editor/Stride.Assets.Presentation/AssetEditors/ScriptEditor/RoslynHost.cs#L50)
- [ProjectWatcher..ctor.AnonymousMethod__13_2() Line 72](https://github.com/stride3d/stride/blob/master/sources/editor/Stride.Assets.Presentation/AssetEditors/ProjectWatcher.cs#L72)

**To Reproduce**
Welp, if you really want to reproduce it, it's fairly involved;
- you can either [build the engine locally](https://github.com/stride3d/stride) or [download it through the launcher](https://www.stride3d.net/download/) and attach your debugger.
- Create any of the samples shown
- Wait for the main window to load in
- The exception should trigger in the background, being caught by your debugger.

**Version**
- OS: Windows
- Build (or commit ID if built from source): latest and previous, see **Additional Information**.

**I'm obviously not asking for you guys to debug our own engine, I would just like to know if you may have some insight into this issue you could share.**

**Comment by aelij** [comment]
Hi @Eideren. I think you need to refresh your `RoslynHost` implementation. What happened is that some of the internal Roslyn types used by RoslynPad (such as `DiagnosticService`) were moved from the `Features` to the `LanguageServer.Protocol` assembly, which needs special handling when loading into MEF. See the `RoslynHost.GetDiagnosticCompositionTypes()` method.

**Comment by Eideren** [comment]
Yep, that was it !
Thanks a whole bunch for getting back to me @aelij
