### ISSUE TITLE
Cannot run code due to RoslynPad.Runtime referencing a higher System.Runtime version.

### ISSUE THREAD

**Issue by MiffOttah** [roslynpad/roslynpad#503]
**Describe the bug**

Attempting to run any C# code under .NET 7.0.302 or .NET 5.0.101 on RoslynPad 19 produces the following error: 

> CS1705: Assembly 'RoslynPad.Runtime' with identity 'RoslynPad.Runtime, Version=4.8.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

.NET Framework x86 produces the following error:

> Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.BadImageFormatException: Could not load file or assembly 'RoslynPad.Runtime, Version=4.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

.NET Framework x64 works.

**To Reproduce**

In RoslynPad, create a new file and enter the following code:

```csharp
Console.WriteLine("Hello, world!");
```

Select .NET 7.0.302 and then select Run

**Expected behavior**

"Hello, world!" appears under Results.

**Version**
- OS: Windows 11 23H2 build 22631.2715
- Build (or commit ID if built from source): 19

![screenshot_23-12-07_20 12 28](https://github.com/roslynpad/roslynpad/assets/511411/2250d727-2fd3-4452-8a8c-ac636409f789)

**Comment by aelij** [comment]
Hi @MiffOttah. I will fix .NET 7, that was an oversight. Also, do you really need x86 support? Thinking of removing it.
