### ISSUE TITLE
Errors are not underlined in 19.1

### ISSUE THREAD

**Issue by DamianSuess** [roslynpad/roslynpad#506]
**Describe the bug**

After upgrading to v19.1 (from v18), errors in code are no longer underlined with a red-squiggly. Warnings are still being rendered.

![image](https://github.com/roslynpad/roslynpad/assets/1216684/188357b7-0315-4b81-9921-6307857ca6c1)

![image](https://github.com/roslynpad/roslynpad/assets/1216684/f6442602-4282-4549-98b3-6bba02005af9)

**To Reproduce**

1. Extract v19.1 package contents
2. Open a new tab and type, `asdf`
3. Code error is not underlined in red

**Expected behavior**

Underline errors in code using the red squiggly

**Version**
- OS: Windows 10
- Build (or commit ID if built from source):

**Comment by DustyJoeJoe** [comment]
I gave the same issues exactly, except all my code is in *.csx files

I attempted and failed to correct this with a .editorconfig (it doesnt seem to be loading the file at all, no error, no setting changes...)

I have reverted back to version 18 and there the "new version available" wart wont go away and renders on top of ui elements forever now

**Comment by DamianSuess** [comment]
@aelij, I was poking around to see what has changed in the code, but couldn't find anything. I'm surprised to see that not performing `PublishSingleFile` was the fix for the issue. None the less, thank you for the quick turn around! nice catch
