### ISSUE TITLE
On Mac version, pressing Esc to dismiss the Save dialog crashes the app

### ISSUE THREAD

**Issue by Doodpants** [roslynpad/roslynpad#536]
RoslynPad on Mac unexpectedly quits if I press the Escape key when the Save dialog is open.

**To Reproduce**
Launch RoslynPad on the Mac, write some code, and then click the Save button. While the Save dialog is visible, press the Escape key.

**Expected behavior**
The Save dialog should dismiss without the application crashing

**Version**
- OS: macOS 14.5
- Build (or commit ID if built from source): 19.1.0

**Comment by aelij** [comment]
I think this is fixed in the main branch, as I've switched away from OS save dialogs to something like the Windows version. Please check v20 once it's realeased.
