### ISSUE TITLE
The Mac version should use the Cmd key for shortcuts instead of Ctrl

### ISSUE THREAD

**Issue by Doodpants** [roslynpad/roslynpad#539]
Currently, keyboard shortcuts use the Ctrl key (such as Ctrl+N, Ctrl+S, Ctrl+O, etc.). On the Mac, keyboard shortcuts should use the Cmd key instead, especially for standard commands such as those listed above.

**Version**
- OS: macOS 14.5
- Build (or commit ID if built from source): 19.1.0

**Comment by aelij** [comment]
Fixed in d7e03b0
