### ISSUE TITLE
.NET SDK not found when installed by scoop.sh

### ISSUE THREAD

**Issue by Roemer** [roslynpad/roslynpad#546]
**Describe the bug**
When installing everything with scoop (especially the .NET SDK), roslynpad always shows the missing SDK warning.
The variable `DOTNET_ROOT` is set to `C:\Users\rbaer\scoop\apps\dotnet-sdk\current`  which seems to be correct.

**To Reproduce**
- scoop install roslynpad
- scoop install windowsdesktop-runtime
- scoop install dotnet-sdk
- Startuo RoslynPad -> shows the error

**Expected behavior**
No error is shown

**Version**
- OS: Windows 11
- Build (or commit ID if built from source): 19.1

**Comment by Roemer** [comment]
Aha, I think this is fixed in the code now (https://github.com/roslynpad/roslynpad/issues/511) but it is still not released yet.

**Comment by aelij** [comment]
Yes it should be fixed in the main branch and a release is overdue :)
