### ISSUE TITLE
winget app launch error

### ISSUE THREAD

**Issue by Auto72** [roslynpad/roslynpad#553]
**Describe the bug**
winget install --id RoslynPad.RoslynPad

The App is installed, but then when I run it, I don't see it.
I tried also to download the .zip file.
Same behaviour.

**To Reproduce**
Run the App

**Expected behavior**
See the App on the screen

**Version**
- OS: Window 11
- Build (or commit ID if built from source): 10.0.22631.4169

**Comment by aelij** [comment]
Apparently this is a known [winget issue](https://github.com/microsoft/winget-cli/issues/2711).
You can work around it by using `start RoslynPad` in PowerShell and then pinning it to the taskbar.
