### ISSUE TITLE
disable automatic insertion of using directives

### ISSUE THREAD

**Issue by lupokk** [roslynpad/roslynpad#554]
I wanted to ask if it is possible to disable the automatic insertion of "using" directives. 
In summary, when you select a class from code completion, the editor automatically adds the "using" directive if it is missing. Is it possible to disable this option?

![image](https://github.com/user-attachments/assets/545f418d-6328-48a0-98a2-38adeb276cbd)

**Comment by aelij** [comment]
There is such an option in Roslyn but it's not exposed in RP - https://github.com/dotnet/roslyn/blob/33f853a8638d9254a04a5830870067f51f8dd63c/src/Features/Core/Portable/Completion/CompletionOptions.cs#L23

**Comment by lupokk** [comment]
Thanks for the quick response. I don't understand though, is Roslyn adding the "using..." line? If I understand correctly, the option you highlighted should limit the elements of the completion. I didn't ask for that, I asked that the system not add the "using" line.

**Comment by aelij** [comment]
It's the same feature. If Roslyn shows unimported items in the completion menu, it will add the `using` when it commits such an item.

**Comment by lupokk** [comment]
thanks @aelij, is there a way to set ShowItemsFromUnimportedNamespaces to false by recompiling RP?

**Comment by aelij** [comment]
Yeah, but wouldn't you prefer posting a PR and adding a setting?

**Comment by MatthewB05** [comment]
Hi,

I'm not sufficiently familiar with the code base to know where the best place would be to connect a setting, but I was able to remove the unwanted completion items by 1) adding the below as RoslynPad.Roslyn/Completion/CompletionProviderExtensions.cs :

````
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Completion;
using Microsoft.CodeAnalysis.Options;

namespace RoslynPad.Roslyn.Completion;

public static class CompletionProviderExtensions
{
    public static Task<CompletionList> GetCompletionsImportedOnlyAsync(
        this CompletionService service,
        Document document,
        int caretPosition,
        CompletionTrigger trigger = default,
        ImmutableHashSet<string>? roles = null,
        OptionSet? options = null,
        CancellationToken cancellationToken = default
        )
    {
        var completionOptions = CompletionOptions.Default with { ForceExpandedCompletionIndexCreation = true, ShowItemsFromUnimportedNamespaces = false };
        var passThroughOptions = options ?? document.Project.Solution.Options;

        return service.GetCompletionsAsync(document, caretPosition, completionOptions, passThroughOptions, trigger, roles, cancellationToken);
    }
}
````

And then 2) by changing RoslynPad.Editor.Windows/Shared/RoslynCodeEditorCompletionProvider.cs to use the above in place of GetCompletionsAsync() :

````
            var data = await completionService.GetCompletionsImportedOnlyAsync(
                document,
                position,
                completionTrigger
                ).ConfigureAwait(false);
````

**Comment by lupokk** [comment]
@MatthewB05, I think it's a good solution, thank you very much.
