### ISSUE TITLE
[Feature] Publish and use SingleFile flag for a single executable output

### ISSUE THREAD

**Issue by brmassa** [roslynpad/roslynpad#566]
**Describe the solution you'd like**
The GitHub action build process is using `dotnet build` to compile the code. For final products, the command should be dotnet publish, that will also perform a series of optimizations. One such possible optimization is --PublishSingleFile=true that will include all the DLLs inside the executable itself. Much cleaner.

- change the `.github/workflows/build.yml`  to use dotnet publish
- include `--PublishSingleFile=true`in the command

**Comment by aelij** [comment]
I've tried this before and it caused issues in loading assemblies at runtime, so not high on my priority list.

**Comment by aelij** [comment]
Closing for now

**Comment by brmassa** [comment]
@aelij , i dont understand why closing the issue.

`dotnet publish` is the intended way for releasing .Net apps, not just `build`. It might be not in the priority list, but it's a potencial source of performance.

the `--PublishSingleFile=true` is optional (and should be only done for dotnet 6+), despite being a good quality enhancement forthe final build.

**Comment by aelij** [comment]
I'm already using it, see https://github.com/roslynpad/roslynpad/blob/main/deploy/CreatePackages.ps1#L102
The build yaml your referred to is only used to validate PRs.
