### ISSUE TITLE
Reference shared frameworks or select SDK (support ASP.NET)

### ISSUE THREAD

**Issue by qoh** [roslynpad/roslynpad#568]
**Describe the solution you'd like**
I want to experiment with ASP.NET and use ASP.NET types in RoslynPad.

ASP.NET is delivered as:
- A shared framework you can use with `<FrameworkReference Include="Microsoft.AspNetCore.App" />`.
- An SDK you can use with `<Project Sdk="Microsoft.NET.Sdk.Web">`.

Any of the following would work:
- Recognize shared frameworks (package type DotnetPlatform) in the `#r` directive and use the equivalent of `<FrameworkReference>` instead of `<PackageReference>` (assuming `#r` is a part of RoslynPad).
- A new directive for referencing shared frameworks.
- An option to select the project SDK to use for the document, like how you can select the .NET version.

**Describe alternatives you've considered**
I tried to reference some ASP.NET assemblies as packages, but [this no longer works since .NET Core 3.0](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-8.0&tabs=visual-studio#use-the-aspnet-core-shared-framework). The packages that do exist don't contain most of the types you'd expect or would find in the documentation.

**Additional context**
Attempting to load the shared framework with `#r "nuget: Microsoft.AspNetCore.App.Ref, 8.0.10"` errors:
> NU1213: The package Microsoft.AspNetCore.App.Ref 8.0.10 has a package type DotnetPlatform that is incompatible with this project.

[CSharpRepl](https://github.com/waf/CSharpRepl?tab=readme-ov-file#adding-references) supports selecting the SDK at startup time with a `--framework Microsoft.AspNetCore.App` command-line argument.

**Comment by aelij** [comment]
Hi, this is already possible using `#r "framework: Microsoft.AspNetCore.App"`.

**Comment by qoh** [comment]
Is that documented anywhere? If not, it might be good to mention.

**Comment by aelij** [comment]
As there's no doc site for RP, I wouldn't know where to put it. :) perhaps just add a button "add framework reference" that adds an empty `#r "framework: "`.
